[package]
name = "risc-v-sandbox"
version = "0.0.0"
edition = "2021"

[dependencies]
goblin = "0.7.1"
rvemu = "0.0.11"
derive_more = "0.99.17"

[dependencies.clap]
version = "4.4.6"
features = ["derive"]

[dependencies.kernel-loader]
version = "0.1.0"
path = "../kernel_loader"

