# SPDX-FileCopyrightText: 2022-2023 TriliTech <contact@trili.tech>
# SPDX-FileCopyrightText: 2023 Marigold <contact@marigold.dev>
#
# SPDX-License-Identifier: MIT

[package]
name = "kernel-benchmark"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
evm-execution.workspace = true
tezos_ethereum.workspace = true
thiserror.workspace = true
hex.workspace = true
rlp.workspace = true
sha3.workspace = true
tezos_data_encoding.workspace = true
primitive-types.workspace = true
evm.workspace = true

tezos-smart-rollup-core.workspace = true
tezos-smart-rollup-host.workspace = true
tezos-smart-rollup-debug.workspace = true
tezos-smart-rollup-encoding.workspace = true
tezos-smart-rollup-entrypoint.workspace = true
tezos-smart-rollup-mock.workspace = true

[features]
default = ["evm_kernel_benchmark"]
testing = []
evm_kernel_benchmark = []
