octogram_binary:
  push: octogram

agents:
  - name: node
    address: 127.0.0.1
    user: root
    port: 30000
    identity: ~/.ssh/tf

  - name: localhost
    address: 127.0.0.1
    user: root
    port: 30000
    identity: ~/.ssh/tf

vars:
  network: sandbox
  alias_prefix: bootstrap
  keys_base_dir: fresh_wallet
  number_of_shards: 2048
  page_size: 4096
  slot_size: 65536
  redundancy_factor: 2

stages:
  - name: Initialize protocol file
    with_agents: 'localhost'
    run_agents: concurrent
    jobs:
      - name: Upload protocol file
        copy:
          local_path: 'src/proto_alpha/parameters/{{ vars.network }}-parameters.json'
          remote_path: '.'

      - name: Upload octez-client
        copy:
          local_path: octez-client
          remote_path: '.'

      - name: Generate keys
        tezos.generate_keys:
          base_dir: 'self://{{ vars.keys_base_dir }}'
          kind:
             default: # We currently re-use default Tezt keys
             # for when we want fresh keys
             # fresh:
             #   count: 10
             #   path_client: 'self://./octez-client'
             #   alias_prefix: '{{ vars.alias_prefix }}'

      - name: Compress generated keys
        builtins.tar:
          contents: '{{ vars.keys_base_dir }}'
          archive: 'self://{{ vars.keys_base_dir }}.tar.gz'
          action: create

      - name: Start HTTP server
        builtins.start_http_server:
          http_port: '30999'

  - name: Running nodes
    with_agents: 'node'
    run_agents: concurrent
    jobs:
      - name: Pull protocol parameters file
        builtins.prefetch: 'localhost://sandbox-parameters.json'

      - name: Pull generated keys
        builtins.prefetch: 'localhost://{{ vars.keys_base_dir }}.tar.gz'

      - name: Uncompress generated keys
        builtins.tar:
          contents: 'my-unique-baker'
          archive: 'self://{{ vars.keys_base_dir }}.tar.gz'
          action: extract

      - name: Upload octez binaries
        run_items: concurrent
        copy:
          local_path: '{{ item }}'
          remote_path: '.'
        with_items:
          - octez-node
          - octez-client
          - octez-baker-alpha
          - octez-dal-node

      - name: Start octez-node
        tezos.start_node:
          name: node
          path_node: self://./octez-node
          network: '{{ vars.network }}'
          synchronization_threshold: 0
          rpc_port: '30001'
          metrics_port: '30002'
          net_port: '30003'
          dal_cryptobox_parameters:
            number_of_shards: '{{ vars.number_of_shards }}'
            page_size: '{{ vars.page_size }}'
            slot_size: '{{ vars.slot_size }}'
            redundancy_factor: '{{ vars.redundancy_factor }}'

      - name: Activate protocol
        tezos.activate_protocol:
          endpoint: self://node
          path_client: self://./octez-client
          protocol: alpha
          parameter_file: 'self://sandbox-parameters.json'

      - name: Wait for bootstrapped node
        tezos.wait_for_bootstrapped:
          path_client: self://./octez-client
          endpoint: self://node

      - name: Start octez-dal-node
        tezos.start_dal_node:
          name: dal_node
          path_node: self://./octez-dal-node
          rpc_port: '30011'
          metrics_port: '30012'
          net_port: '30013'
          l1_node_uri: self://node
          bootstrap_profile: false
          attestor_profiles:
           - tz1foXHgRzdYdaLgX6XhpZGxbBv42LZ6ubvE
           - tz1gBnaS1n7LKqpaRnyBX5MSmamadXXfzNpt
           - tz1YtB3Hn6oghVk96vkpZt6PHrfbyRY1ciL3
          producer_profiles:
           - 1
           - 3
           - 55
           - 94

      - name: Start octez-baker-alpha
        tezos.start_baker:
          name: my-unique-baker
          protocol: alpha
          base_dir: 'self://my-unique-baker/{{ vars.keys_base_dir }}'
          node_uri: self://node
          dal_node_uri: self://dal_node
          delegates:
           - bootstrap1
           - bootstrap2
           - bootstrap3
           - bootstrap4
           - bootstrap5
