# SPDX-FileCopyrightText: 2023 TriliTech <contact@trili.tech>
# SPDX-FileCopyrightText: 2023 Nomadic Labs <contact@nomadic-labs.com>
# SPDX-FileCopyrightText: 2023 Marigold <contact@marigold.dev>
#
# SPDX-License-Identifier: MIT

[package]
name = "evm-execution"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
thiserror.workspace = true
hex.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
rlp.workspace = true

tezos_data_encoding.workspace = true
tezos_crypto_rs.workspace = true

# Adding these to 'dev_dependencies' causes the rand feature in crypto to be enabled
# on wasm builds, when building the entire workspace.
rand = { version = "0.8", optional = true }
proptest = { workspace = true, optional = true }
evm.workspace = true
primitive-types.workspace = true
sha2.workspace = true
sha3.workspace = true
ripemd.workspace = true
libsecp256k1.workspace = true
const-decoder.workspace = true

tezos_ethereum.workspace = true

tezos-smart-rollup-core.workspace = true
tezos-smart-rollup-host.workspace = true
tezos-smart-rollup-debug.workspace = true
tezos-smart-rollup-encoding.workspace = true
tezos-smart-rollup-mock.workspace = true
tezos-smart-rollup-storage.workspace = true

[features]
default = ["evm_execution"]
testing = ["rand", "proptest"]
evm_execution = []
