# SPDX-FileCopyrightText: 2023 Nomadic Labs <contact@nomadic-labs.com>
# SPDX-FileCopyrightText: 2023 Marigold <contact@marigold.dev>
#
# SPDX-License-Identifier: MIT

[workspace]

members = [
  "ethereum",
  "kernel",
  "evm_execution",
  "kernel_benchmark",
  "logging"
]

[workspace.dependencies]

rlp = "0.5.2"
thiserror = "1.0"
anyhow = "1.0"
evm = { version = "0.35.0", default-features = false }
primitive-types = { version = "0.11.1", default-features = false }
hex = "0.4"
hex-literal = "0.4.1"
num-traits = "0.2.8"
sha2 = { version = "0.10.6", default-features = false }
sha3 = { version = "0.10.6", default-features = false }
ripemd = { version = "0.1.3", default-features = false }
tezos_crypto_rs = { version = "0.5", default-features = false }
libsecp256k1 = { version = "0.7", default-features = false, features = ["static-context", "hmac"] }
tezos_data_encoding = "0.5"
num-bigint = "0.3"
const-decoder = { version = "0.3.0" }
proptest = { version = "1.0" }

# Kernel crates
tezos_ethereum = { path = "./ethereum" }
evm-execution = { path = "./evm_execution" }
tezos-evm-logging = { path = "./logging" }

# SDK
tezos-smart-rollup-core = { path = "../kernel_sdk/core", features = ["proto-nairobi"] }
tezos-smart-rollup-host = { path = "../kernel_sdk/host", features = ["proto-nairobi"] }
tezos-smart-rollup-panic-hook = { path = "../kernel_sdk/panic-hook" }
tezos-smart-rollup-entrypoint = { path = "../kernel_sdk/entrypoint" }
tezos-smart-rollup-debug = { path = "../kernel_sdk/debug" }
tezos-smart-rollup-encoding = { path = "../kernel_sdk/encoding" }
tezos-smart-rollup-installer-config = { path = "../kernel_sdk/installer-config" }
tezos-smart-rollup-mock = { path = "../kernel_sdk/mock", features = ["proto-nairobi"] }
tezos-smart-rollup-storage = { path = "../kernel_sdk/storage" }
